# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed

# Setup
title:            'Seth Gholson'
tag_text:          'A developer'
description:      'Software dev in Austin, TX focused on Android'
baseurl:          /

author:           'sethgho@gmail.com'
name:           'Seth Gholson'
url:            'http://www.sethgholson.com'

twitter:          http://twitter.com/sethgho
github:
github:             https://github.com/sethgho
gravatar:         'd704ea2a2f1bb79d9719b451505e7b3d'